runtime: python39
entrypoint: gunicorn -b :$PORT backend.wsgi

handlers:
- url: /.*
  script: auto

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2